#!/bin/bash

spin ()
{
    i=1
    while [[ 1 ]]
    do
        sleep 1
        printf "\r$1: %d" ${i}
        i=$(( ${i} + 1 ))
        wait
    done
}

RED='\033[0;31m'
NC='\033[0m'

printf "Enter password for $USER: "
IFS= read -rs password
sudo -k
until sudo -lS &> /dev/null << EOF
$password
EOF
do
    printf "\n${RED}Password is incorect!\n${NC}"
    printf "Enter password for $USER: "
	IFS= read -rs password
done

printf "\nEnter project path root: "
read projectFolder
until [[ -d "${projectFolder}" ]];
do
    printf "${RED}${projectFolder} is a directory\n${NC}"
    printf 'Enter project path root: '
	read projectFolder
done

printf 'HTTP group (default: www-data): '
read HTTPDUSER

spin 'Running' &
pid=$!

cd "${projectFolder}" &&
sudo chown -R `whoami`:"$HTTPDUSER" . && 
sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX var pub/static pub/media app/etc generated && 
sudo setfacl -dR -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX var pub/static pub/media app/etc generated && 
find . -type d -exec chmod 775 {} \; && find . -type f -exec chmod 664 {} \; && 
chmod u+x bin/magento

kill ${pid}
printf "\nDone!"